[program:ptt-fleet-api]
directory=/opt/ptt-fleet/api-server
command=/opt/ptt-fleet/api-server/run-with-env.sh
user=ptt-fleet
autostart=true
autorestart=unexpected
startsecs=5
startretries=5
stopsignal=TERM
stopwaitsecs=20
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/ptt-fleet/api-server.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=HOME="/opt/ptt-fleet",USER="ptt-fleet"
